# Generated by Django 5.1.2 on 2024-11-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=200, null=True)),
                ('mota', models.TextField(max_length=400)),
                ('donvitinh', models.CharField(choices=[('kg', 'kg'), ('cai', 'cái'), ('chai', 'chai'), ('hop', 'hộp')], default='cao', max_length=4)),
                ('kho', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=100, null=True)),
                ('diachi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhoHangHoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField(default=0)),
                ('HangHoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.hanghoa')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.kho')),
            ],
        ),
    ]
