# Generated by Django 5.1.2 on 2024-11-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlkhohang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khohanghoa',
            old_name='HangHoa',
            new_name='hanghoa',
        ),
        migrations.RenameField(
            model_name='khohanghoa',
            old_name='SoLuong',
            new_name='soluong',
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='kho',
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='donvitinh',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('CAI', 'Cái'), ('CHAI', 'Chai'), ('HOP', 'Hộp')], max_length=4),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='mota',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='ten',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
